spring.application.name=service1-producer
# Server
server.port=8081

# H2 Database
spring.datasource.url=jdbc:h2:mem:producerdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Kafka Producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# App Config
kafka.topic=user-raw
outbox.scheduler.delay-ms=3000