spring.application.name=service2-transformer
# Server
server.port=8082

# H2 Database
spring.datasource.url=jdbc:h2:mem:transformerdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Kafka Consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=transformer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.max-poll-records=10

# App Config
kafka.topic=user-raw
kafka.consumer.concurrency=3
service3.url=http://localhost:8083

spring.sql.init.mode=always